
export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <header className="my-12">
        <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl text-center">
          Terms of Service
        </h1>
        <p className="mt-4 text-lg text-muted-foreground text-center">
          Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </header>
      <div className="prose prose-invert mx-auto">
        <p>
          Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the WillItTrend.com website (the "Service") operated by WillItTrend.com ("us", "we", or "our").
        </p>
        
        <h2 className="text-2xl font-semibold mt-8">1. Agreement to Terms</h2>
        <p>
          By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8">2. Use of Service</h2>
        <p>
            Our Service provides AI-powered trend forecasting and content generation tools. You are responsible for the inputs you provide and for your use of the generated outputs. You agree not to use the Service for any unlawful purpose or in any way that interrupts, damages, or impairs the service.
        </p>
        <p>
            The predictions and content generated by our AI are for informational purposes only and are not guaranteed to be accurate or to produce specific results. You agree to use the outputs at your own discretion and risk.
        </p>

        <h2 className="text-2xl font-semibold mt-8">3. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are and will remain the exclusive property of WillItTrend.com and its licensors.
        </p>

        <h2 className="text-2xl font-semibold mt-8">4. Limitation of Liability</h2>
        <p>
          In no event shall WillItTrend.com, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8">5. Disclaimer</h2>
        <p>
            Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8">6. Changes</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8">Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at: <a href="mailto:ai@incdrops.com" className="text-primary hover:underline">ai@incdrops.com</a>
        </p>
      </div>
    </div>
  );
}
